#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Nov 05, 2018 02:38:36 AM EST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family Verdana -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family {Droid Sans Mono} -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Verdana -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m41" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 758x629+156+48
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1009 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "GUI"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m41
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    frame $top.fra42 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 295 \
        -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra42" "MM_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra42
    entry $site_3_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable gtp_x 
    vTcl:DefineAlias "$site_3_0.ent43" "Entry_gtp_x" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text Micromanipulator 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_Manipulator" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable gtp_y 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry_gtp_y" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable gtp__z 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry_gtp_z" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Go To Position (um)} 
    vTcl:DefineAlias "$site_3_0.but48" "Button_gtp" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text x 
    vTcl:DefineAlias "$site_3_0.but49" "Button_step_x" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Step (um)} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_step" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text y 
    vTcl:DefineAlias "$site_3_0.but52" "Button_step_y" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text z 
    vTcl:DefineAlias "$site_3_0.but53" "Button_step_z" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but61 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Set Origin} 
    vTcl:DefineAlias "$site_3_0.but61" "Button_setorigin" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Change Velocity (um/s)} 
    vTcl:DefineAlias "$site_3_0.but42" "Button_velocity" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable velocity 
    vTcl:DefineAlias "$site_3_0.ent44" "Entry_velocity" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi50 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_x -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi50" "Spinbox_step_x" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi51 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_z -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi51" "Spinbox_step_z" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi52 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_y -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi52" "Spinbox_step_y" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {High Resolution} -value high \
        -variable radio_resolution 
    vTcl:DefineAlias "$site_3_0.rad42" "Radiobutton_highres" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Low Resolution} -value low \
        -variable radio_resolution 
    vTcl:DefineAlias "$site_3_0.rad43" "Radiobutton_lowres" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -state active -text Interrupt 
    vTcl:DefineAlias "$site_3_0.but54" "Button_mm_interrupt" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab40 \
        -background {#d9d9d9} -foreground {#000000} -text {Pathing Function} 
    vTcl:DefineAlias "$site_3_0.lab40" "Label_pathing" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable pathing_func 
    vTcl:DefineAlias "$site_3_0.ent50" "Entry_pathing_func" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent43 \
        -in $site_3_0 -x 20 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 10 -width 136 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 70 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 120 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 80 -y 150 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 20 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 80 -y 180 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 80 -y 210 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 20 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.but42 \
        -in $site_3_0 -x 160 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.ent44 \
        -in $site_3_0 -x 330 -y 130 -width 56 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi50 \
        -in $site_3_0 -x 40 -y 150 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi51 \
        -in $site_3_0 -x 40 -y 210 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 40 -y 180 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad42 \
        -in $site_3_0 -x 170 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.rad43 \
        -in $site_3_0 -x 170 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 310 -y 260 -anchor nw -bordermode ignore 
    place $site_3_0.lab40 \
        -in $site_3_0 -x 210 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.ent50 \
        -in $site_3_0 -x 230 -y 60 -width 136 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra44 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 325 \
        -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra44" "Current_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Current/Power Supply} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_ps" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Interrupt 
    vTcl:DefineAlias "$site_3_0.but69" "Button_ps_interrupt" vTcl:WidgetProc "Toplevel1" 1
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $site_3_0.tNo48 \
        -width 372 -height 223 -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tNo48" "Notebook_ps" vTcl:WidgetProc "Toplevel1" 1
    frame $site_3_0.tNo48.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t0" "Notebook_ps_t1" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo48 add $site_3_0.tNo48.t0 \
        -padding 0 -sticky nsew -state normal -text Constant -image {} \
        -compound left -underline -1 
    set site_5_0  $site_3_0.tNo48.t0
    label $site_5_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Amperes (mA)} 
    vTcl:DefineAlias "$site_5_0.lab49" "Label_constant_amps" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent40 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable constant_amps 
    vTcl:DefineAlias "$site_5_0.ent40" "Entry_constant_amps" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Duration (s)} 
    vTcl:DefineAlias "$site_5_0.lab41" "Label_constant_duration" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_0.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable constant_duration 
    vTcl:DefineAlias "$site_5_0.ent42" "Entry_constant_duration" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_0.but43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Set Configuration} 
    vTcl:DefineAlias "$site_5_0.but43" "Button_constant_setconfig" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Units? 
    vTcl:DefineAlias "$site_5_0.lab55" "Label8" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_0.lab49 \
        -in $site_5_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_5_0.ent40 \
        -in $site_5_0 -x 110 -y 10 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.lab41 \
        -in $site_5_0 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_0.ent42 \
        -in $site_5_0 -x 110 -y 30 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_0.but43 \
        -in $site_5_0 -x 10 -y 60 -anchor nw -bordermode ignore 
    place $site_5_0.lab55 \
        -in $site_5_0 -x 180 -y 30 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo48.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t1" "Notebook_ps_t2" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo48 add $site_3_0.tNo48.t1 \
        -padding 0 -sticky nsew -state normal -text Square -image {} \
        -compound left -underline -1 
    set site_5_1  $site_3_0.tNo48.t1
    label $site_5_1.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Amperes (mA)} 
    vTcl:DefineAlias "$site_5_1.lab45" "Label_square_amps" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_1.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable square_amps 
    vTcl:DefineAlias "$site_5_1.ent46" "Entry_square_amps" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_1.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Duration (s)} 
    vTcl:DefineAlias "$site_5_1.lab47" "Label_square_duration" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_1.ent48 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable square_duration 
    vTcl:DefineAlias "$site_5_1.ent48" "Entry_square_duration" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_1.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Duty Cycle (%)} 
    vTcl:DefineAlias "$site_5_1.lab49" "Label_square_duty" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_1.ent50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable square_duty 
    vTcl:DefineAlias "$site_5_1.ent50" "Entry_square_duty" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_1.but52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Set Configuration} 
    vTcl:DefineAlias "$site_5_1.but52" "Button_square_setconfig" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_1.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Frequency (Hz)} 
    vTcl:DefineAlias "$site_5_1.lab53" "Label_square_freq" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_1.ent54 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black \
        -textvariable square_freq 
    vTcl:DefineAlias "$site_5_1.ent54" "Entry_square_freq" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_1.lab45 \
        -in $site_5_1 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_5_1.ent46 \
        -in $site_5_1 -x 110 -y 10 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_1.lab47 \
        -in $site_5_1 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_1.ent48 \
        -in $site_5_1 -x 110 -y 30 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_1.lab49 \
        -in $site_5_1 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_5_1.ent50 \
        -in $site_5_1 -x 110 -y 50 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_1.but52 \
        -in $site_5_1 -x 10 -y 100 -anchor nw -bordermode ignore 
    place $site_5_1.lab53 \
        -in $site_5_1 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_5_1.ent54 \
        -in $site_5_1 -x 110 -y 70 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo48.t2 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t2" "Notebook_ps_t3" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo48 add $site_3_0.tNo48.t2 \
        -padding 0 -sticky nsew -state normal -text Custom -image {} \
        -compound left -underline -1 
    set site_5_2  $site_3_0.tNo48.t2
    label $site_5_2.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left \
        -text {linear rise, exponential rise, rise time, duration-risetime=steadystate time} \
        -wraplength 200 
    vTcl:DefineAlias "$site_5_2.lab56" "Label9" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_2.lab56 \
        -in $site_5_2 -x 20 -y 30 -width 217 -relwidth 0 -height 98 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.tNo48.t3 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$site_3_0.tNo48.t3" "Notebook_ps_t4" vTcl:WidgetProc "Toplevel1" 1
    $site_3_0.tNo48 add $site_3_0.tNo48.t3 \
        -padding 0 -sticky nsew -state normal -text Sinusoidal -image {} \
        -compound left -underline -1 
    set site_5_3  $site_3_0.tNo48.t3
    entry $site_5_3.ent42 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable sin_freq 
    vTcl:DefineAlias "$site_5_3.ent42" "Entry_sin_freq" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_3.lab43 \
        -background {#d9d9d9} -foreground {#000000} -text {Frequency (Hz)} 
    vTcl:DefineAlias "$site_5_3.lab43" "Label_sin_freq" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_3.lab44 \
        -background {#d9d9d9} -foreground {#000000} -text {Amplitude (mA)} 
    vTcl:DefineAlias "$site_5_3.lab44" "Label_sin_amplitude" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_3.ent45 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable sin_amplitude 
    vTcl:DefineAlias "$site_5_3.ent45" "Entry_sin_amplitude" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_3.lab46 \
        -background {#d9d9d9} -foreground {#000000} -text {Offset (mA)} 
    vTcl:DefineAlias "$site_5_3.lab46" "Label_sin_offset" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_3.ent47 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable sin_offset 
    vTcl:DefineAlias "$site_5_3.ent47" "Entry_sin_offset" vTcl:WidgetProc "Toplevel1" 1
    label $site_5_3.lab48 \
        -background {#d9d9d9} -foreground {#000000} -text {Duration (s)} 
    vTcl:DefineAlias "$site_5_3.lab48" "Label_sin_duration" vTcl:WidgetProc "Toplevel1" 1
    entry $site_5_3.ent49 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black -textvariable sin_duration 
    vTcl:DefineAlias "$site_5_3.ent49" "Entry_sin_duration" vTcl:WidgetProc "Toplevel1" 1
    button $site_5_3.but51 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text {Set Configuration} 
    vTcl:DefineAlias "$site_5_3.but51" "Button_sin_setconfig" vTcl:WidgetProc "Toplevel1" 1
    place $site_5_3.ent42 \
        -in $site_5_3 -x 120 -y 70 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_3.lab43 \
        -in $site_5_3 -x 10 -y 70 -anchor nw -bordermode ignore 
    place $site_5_3.lab44 \
        -in $site_5_3 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_5_3.ent45 \
        -in $site_5_3 -x 120 -y 10 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_3.lab46 \
        -in $site_5_3 -x 10 -y 30 -anchor nw -bordermode ignore 
    place $site_5_3.ent47 \
        -in $site_5_3 -x 120 -y 30 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_3.lab48 \
        -in $site_5_3 -x 10 -y 50 -anchor nw -bordermode ignore 
    place $site_5_3.ent49 \
        -in $site_5_3 -x 120 -y 50 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_5_3.but51 \
        -in $site_5_3 -x 10 -y 100 -anchor nw -bordermode ignore 
    button $site_3_0.but44 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Run 
    vTcl:DefineAlias "$site_3_0.but44" "Button_ps_run" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but57 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Stop 
    vTcl:DefineAlias "$site_3_0.but57" "Button_ps_stop" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 10 -width 175 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 310 -y 280 -anchor nw -bordermode ignore 
    place $site_3_0.tNo48 \
        -in $site_3_0 -x 10 -y 40 -width 372 -relwidth 0 -height 223 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 20 -y 280 -anchor nw -bordermode ignore 
    place $site_3_0.but57 \
        -in $site_3_0 -x 110 -y 280 -anchor nw -bordermode ignore 
    frame $top.fra70 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 425 \
        -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra70" "Status_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text Status 
    vTcl:DefineAlias "$site_3_0.lab72" "Label_status" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Position (um):} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label_status_pos" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Position Mode: } 
    vTcl:DefineAlias "$site_3_0.lab42" "Label_status_posmode" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Resolution: 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_status_res" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Velocity (units?):} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label_status_vel" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Magnetic Field:} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label_status_magfield" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Console Output} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label_console" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes60 \
        -anchor nw -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d8d8d8} -highlightcolor black -relief sunken \
        -text Messages -width 308 
    vTcl:DefineAlias "$site_3_0.mes60" "Message_console" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Value -textvariable status_pos_v 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_status_pos_v" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Value -textvariable status_posmode_v 
    vTcl:DefineAlias "$site_3_0.lab62" "Label_status_posmode_v" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Value -textvariable status_vel_v 
    vTcl:DefineAlias "$site_3_0.lab63" "Label_status_vel_v" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Value -textvariable status_res_v 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_status_res_v" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Value -textvariable status_magfield_v 
    vTcl:DefineAlias "$site_3_0.lab65" "Label_status_magfield_v" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but41 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Refresh 
    vTcl:DefineAlias "$site_3_0.but41" "Button_status_refresh" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#ff0000} \
        -text {STOP ALL} 
    vTcl:DefineAlias "$site_3_0.but52" "Button_master_stop" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 20 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab42 \
        -in $site_3_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 20 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 20 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 270 -anchor nw -bordermode ignore 
    place $site_3_0.mes60 \
        -in $site_3_0 -x 20 -y 290 -width 308 -relwidth 0 -height 90 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 120 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 130 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 140 -y 80 -width 39 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 110 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.lab65 \
        -in $site_3_0 -x 130 -y 120 -anchor nw -bordermode ignore 
    place $site_3_0.but41 \
        -in $site_3_0 -x 260 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 120 -y 390 -anchor nw -bordermode ignore 
    frame $top.fra40 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 195 \
        -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra40" "Frame_demag" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra40
    button $site_3_0.but41 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Start Demagnetization Process} 
    vTcl:DefineAlias "$site_3_0.but41" "Button_demag" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {tkinter messagebox for popup} 
    vTcl:DefineAlias "$site_3_0.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but41 \
        -in $site_3_0 -x 50 -y 50 -width 240 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 50 -y 120 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra42 \
        -in $top -x 0 -y 0 -width 405 -relwidth 0 -height 295 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 0 -y 300 -width 405 -relwidth 0 -height 325 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 410 -y 0 -width 345 -relwidth 0 -height 425 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra40 \
        -in $top -x 410 -y 430 -width 345 -relwidth 0 -height 195 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

