#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Nov 06, 2018 01:16:41 AM EST  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global gtp_x
    gtp_x = StringVar()
    global gtp_y
    gtp_y = StringVar()
    global gtp_z
    gtp_z = StringVar()
    global velocity
    velocity = StringVar()
    global step_x
    step_x = StringVar()
    global step_z
    step_z = StringVar()
    global step_y
    step_y = StringVar()
    global radio_resolution
    radio_resolution = StringVar()
    global pathing_func
    pathing_func = StringVar()
    global constant_amps
    constant_amps = StringVar()
    global constant_duration
    constant_duration = StringVar()
    global square_amp
    square_amp = StringVar()
    global square_duration
    square_duration = StringVar()
    global square_duty
    square_duty = StringVar()
    global square_freq
    square_freq = StringVar()
    global sin_freq
    sin_freq = StringVar()
    global sin_amplitude
    sin_amplitude = StringVar()
    global sin_offset
    sin_offset = StringVar()
    global sin_duration
    sin_duration = StringVar()
    global ramping_amp
    ramping_amp = StringVar()
    global ramping_rise
    ramping_rise = StringVar()
    global ramping_steady
    ramping_steady = StringVar()
    global ramping_rest
    ramping_rest = StringVar()
    global ramping_duration
    ramping_duration = StringVar()
    global status_pos_v
    status_pos_v = StringVar()
    global status_vel_v
    status_vel_v = StringVar()
    global status_res_v
    status_res_v = StringVar()
    global status_magfield_v
    status_magfield_v = StringVar()
    global status_relpos_v
    status_relpos_v = StringVar()
    global status_abspos_v
    status_abspos_v = StringVar()
    global radio_pos_mode
    radio_pos_mode = StringVar()
    global status_current_v
    status_current_v = StringVar()
    global status_wave_v
    status_wave_v = StringVar()
    global status_duration_v
    status_duration_v = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import gui
    gui.vp_start_gui()


