#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 27, 2018 05:38:44 PM EDT  platform: Linux

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global position_mode
    position_mode = StringVar()
    global step_x
    step_x = StringVar()
    global step_z
    step_z = StringVar()
    global step_y
    step_y = StringVar()
    global radio_resolution
    radio_resolution = StringVar()
    global shape
    shape = StringVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import pagegui1
    pagegui1.vp_start_gui()


