#############################################################################
# Generated by PAGE version 4.17
# in conjunction with Tcl version 8.6
# Oct 27, 2018 05:38:31 PM EDT  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family monospace -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family Verdana -size 12 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top39
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top39
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#
    menu .pop51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 1 
    vTcl:DefineAlias ".pop51" "Popupmenu1" vTcl:WidgetProc "" 1

proc vTclWindow.top39 {base} {
    if {$base == ""} {
        set base .top39
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m41" -background {#d9d9d9} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 756x587+141+75
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1009 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "GUI"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m41
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    frame $top.fra42 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 295 \
        -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra42" "MM_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra42
    entry $site_3_0.ent43 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent43" "Entry_gtp_x" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text Micromanipulator 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_Manipulator" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry_gtp_y" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent47 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent47" "Entry_gtp_z" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but48 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Go To Position (um)} 
    vTcl:DefineAlias "$site_3_0.but48" "Button_gtp" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but49 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text x 
    vTcl:DefineAlias "$site_3_0.but49" "Button_step_x" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Move Step/um} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_step" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text y 
    vTcl:DefineAlias "$site_3_0.but52" "Button_step_y" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text z 
    vTcl:DefineAlias "$site_3_0.but53" "Button_step_z" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but61 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Set Origin} 
    vTcl:DefineAlias "$site_3_0.but61" "Button_setorigin" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad40 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Relative -value relative -variable position_mode 
    vTcl:DefineAlias "$site_3_0.rad40" "Radiobutton_relative" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad41 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Absolute -value absolute -variable position_mode 
    vTcl:DefineAlias "$site_3_0.rad41" "Radiobutton_absolute" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Change Velocity} 
    vTcl:DefineAlias "$site_3_0.but42" "Button_velocity" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent44 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent44" "Entry_velocity" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi50 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_x -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi50" "Spinbox_step_x" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi51 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_z -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi51" "Spinbox_step_z" vTcl:WidgetProc "Toplevel1" 1
    spinbox $site_3_0.spi52 \
        -activebackground {#f9f9f9} -background white -foreground black \
        -from -50.0 -highlightbackground black -highlightcolor black \
        -increment 1.0 -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable step_y -to 50.0 
    vTcl:DefineAlias "$site_3_0.spi52" "Spinbox_step_y" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad42 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {High Resolution} -value high \
        -variable radio_resolution 
    vTcl:DefineAlias "$site_3_0.rad42" "Radiobutton_highres" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text {Low Resolution} -value low \
        -variable radio_resolution 
    vTcl:DefineAlias "$site_3_0.rad43" "Radiobutton_lowres" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but54 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Interrupt 
    vTcl:DefineAlias "$site_3_0.but54" "Button_mm_interrupt" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.ent43 \
        -in $site_3_0 -x 20 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 10 -width 136 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 70 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent47 \
        -in $site_3_0 -x 120 -y 40 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 80 -y 150 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 20 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.but52 \
        -in $site_3_0 -x 80 -y 180 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but53 \
        -in $site_3_0 -x 80 -y 210 -width 32 -height 26 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but61 \
        -in $site_3_0 -x 20 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.rad40 \
        -in $site_3_0 -x 190 -y 30 -anchor nw -bordermode ignore 
    place $site_3_0.rad41 \
        -in $site_3_0 -x 190 -y 50 -width 83 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but42 \
        -in $site_3_0 -x 200 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.ent44 \
        -in $site_3_0 -x 330 -y 100 -width 56 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi50 \
        -in $site_3_0 -x 40 -y 150 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi51 \
        -in $site_3_0 -x 40 -y 210 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.spi52 \
        -in $site_3_0 -x 40 -y 180 -width 38 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.rad42 \
        -in $site_3_0 -x 200 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.rad43 \
        -in $site_3_0 -x 200 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.but54 \
        -in $site_3_0 -x 310 -y 260 -anchor nw -bordermode ignore 
    frame $top.fra44 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 285 \
        -highlightcolor black -width 405 
    vTcl:DefineAlias "$top.fra44" "Current_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black \
        -text {Current/Power Supply} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_supply" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent46 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent46" "Entry_amps" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Amperes (mA)} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label_amps" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Duration (s)} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_duration" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent55 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent55" "Entry_duration" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent57 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent57" "Entry_frequency" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Frequency (kHz)} 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_frequency" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Shape 
    vTcl:DefineAlias "$site_3_0.lab63" "Label_shape" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but64 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Set Configuration} 
    vTcl:DefineAlias "$site_3_0.but64" "Button_configuration" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but65 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Begin Experiment} 
    vTcl:DefineAlias "$site_3_0.but65" "Button_begin" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but66 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Stop Experiment} 
    vTcl:DefineAlias "$site_3_0.but66" "Button_stop" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but69 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Interrupt 
    vTcl:DefineAlias "$site_3_0.but69" "Button_ps_interrupt" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but43 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Change Current} 
    vTcl:DefineAlias "$site_3_0.but43" "Button_current" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad52 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Shape1 -value shape1 -variable shape 
    vTcl:DefineAlias "$site_3_0.rad52" "Radiobutton_shape1" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad53 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Shape2 -value shape2 -variable shape 
    vTcl:DefineAlias "$site_3_0.rad53" "Radiobutton_shape2" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad54 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Shape3 -value shape3 -variable shape 
    vTcl:DefineAlias "$site_3_0.rad54" "Radiobutton_shape3" vTcl:WidgetProc "Toplevel1" 1
    radiobutton $site_3_0.rad55 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -justify left -text Shape4 -value shape4 -variable shape 
    vTcl:DefineAlias "$site_3_0.rad55" "Radiobutton_shape4" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 10 -width 175 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent46 \
        -in $site_3_0 -x 120 -y 30 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 12 -y 30 -width 87 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 10 -y 50 -width 79 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 120 -y 50 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent57 \
        -in $site_3_0 -x 120 -y 70 -width 46 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 10 -y 70 -width 104 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 10 -y 90 -width 44 -height 18 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 30 -y 180 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 190 -y 30 -width 125 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but66 \
        -in $site_3_0 -x 190 -y 60 -width 119 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but69 \
        -in $site_3_0 -x 310 -y 250 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 30 -y 210 -anchor nw -bordermode ignore 
    place $site_3_0.rad52 \
        -in $site_3_0 -x 60 -y 90 -anchor nw -bordermode ignore 
    place $site_3_0.rad53 \
        -in $site_3_0 -x 60 -y 110 -anchor nw -bordermode ignore 
    place $site_3_0.rad54 \
        -in $site_3_0 -x 60 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.rad55 \
        -in $site_3_0 -x 60 -y 150 -anchor nw -bordermode ignore 
    frame $top.fra70 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 425 \
        -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra70" "Status_Frame" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font $::vTcl(fonts,vTcl:font9,object) \
        -foreground {#000000} -highlightcolor black -text Status 
    vTcl:DefineAlias "$site_3_0.lab72" "Label_status" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab41 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Position (um): x, y, z} 
    vTcl:DefineAlias "$site_3_0.lab41" "Label_status_position" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab42 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Position Mode: } 
    vTcl:DefineAlias "$site_3_0.lab42" "Label_status_posmode" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Resolution: 
    vTcl:DefineAlias "$site_3_0.lab45" "Label_status_resolution" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Amperes (mA):} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label_status_amps" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Time Remaining (s):} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label_status_duration" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Frequency (kHz):} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label_status_frequency" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Velocity (units?):} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label_status_velocity" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text Shape: 
    vTcl:DefineAlias "$site_3_0.lab50" "Label_status_shape" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Magnetic Field (B):} 
    vTcl:DefineAlias "$site_3_0.lab56" "Label_magnetic_field" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Console Output} 
    vTcl:DefineAlias "$site_3_0.lab59" "Label_console" vTcl:WidgetProc "Toplevel1" 1
    message $site_3_0.mes60 \
        -anchor nw -background {#ffffff} -foreground {#000000} \
        -highlightbackground {#d8d8d8} -highlightcolor black -relief sunken \
        -text Messages -width 308 
    vTcl:DefineAlias "$site_3_0.mes60" "Message_console" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab72 \
        -in $site_3_0 -x 10 -y 10 -anchor nw -bordermode ignore 
    place $site_3_0.lab41 \
        -in $site_3_0 -x 20 -y 40 -anchor nw -bordermode ignore 
    place $site_3_0.lab42 \
        -in $site_3_0 -x 20 -y 60 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 20 -y 100 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 20 -y 130 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 20 -y 150 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 20 -y 170 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 20 -y 80 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 20 -y 190 -anchor nw -bordermode ignore 
    place $site_3_0.lab56 \
        -in $site_3_0 -x 20 -y 220 -anchor nw -bordermode ignore 
    place $site_3_0.lab59 \
        -in $site_3_0 -x 20 -y 250 -anchor nw -bordermode ignore 
    place $site_3_0.mes60 \
        -in $site_3_0 -x 20 -y 270 -width 308 -relwidth 0 -height 150 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra40 \
        -borderwidth 2 -relief raised -background {#d9d9d9} -height 155 \
        -width 345 
    vTcl:DefineAlias "$top.fra40" "Frame_demag" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra40
    button $site_3_0.but41 \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {Start Demagnetization Process} 
    vTcl:DefineAlias "$site_3_0.but41" "Button_demag" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab43 \
        -background {#d9d9d9} -foreground {#000000} \
        -text {tkinter messagebox for popup} 
    vTcl:DefineAlias "$site_3_0.lab43" "Label1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.but41 \
        -in $site_3_0 -x 50 -y 50 -width 240 -relwidth 0 -height 58 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 50 -y 120 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra42 \
        -in $top -x 0 -y 0 -width 405 -relwidth 0 -height 295 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 0 -y 300 -width 405 -relwidth 0 -height 285 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 410 -y 0 -width 345 -relwidth 0 -height 425 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra40 \
        -in $top -x 410 -y 430 -width 345 -relwidth 0 -height 155 \
        -relheight 0 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top39 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

